name: Build Absence Manager
on: [push]
jobs:
  build:
    name: Build Absence Manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: install packages
        run: |
          yarn install --frozen-lockfile
      - name: build project
        run: |
          yarn build
      - name: test project
        run: |
          yarn test